//
//  JointType.swift
//  BrainPower
//
//  Created by user on 8/13/24.
//

import Foundation

enum JointType: String, CaseIterable {
    case root = "root"
    case hips = "hips_joint"
    case leftUpLeg = "left_upLeg_joint"
    case leftLeg = "left_leg_joint"
    case leftFoot = "left_foot_joint"
    case leftToes = "left_toes_joint"
    case leftToesEnd = "left_toesEnd_joint"
    case rightUpLeg = "right_upLeg_joint"
    case rightLeg = "right_leg_joint"
    case rightFoot = "right_foot_joint"
    case rightToes = "right_toes_joint"
    case rightToesEnd = "right_toesEnd_joint"
    case spine1 = "spine_1_joint"
    case spine2 = "spine_2_joint"
    case spine3 = "spine_3_joint"
    case spine4 = "spine_4_joint"
    case spine5 = "spine_5_joint"
    case spine6 = "spine_6_joint"
    case spine7 = "spine_7_joint"
    case leftShoulder = "left_shoulder_1_joint"
    case leftArm = "left_arm_joint"
    case leftForearm = "left_forearm_joint"
    case leftHand = "left_hand_joint"
    case leftHandIndexStart = "left_handIndexStart_joint"
    case leftHandIndex1 = "left_handIndex_1_joint"
    case leftHandIndex2 = "left_handIndex_2_joint"
    case leftHandIndex3 = "left_handIndex_3_joint"
    case leftHandIndexEnd = "left_handIndexEnd_joint"
    case leftHandMidStart = "left_handMidStart_joint"
    case leftHandMid1 = "left_handMid_1_joint"
    case leftHandMid2 = "left_handMid_2_joint"
    case leftHandMid3 = "left_handMid_3_joint"
    case leftHandMidEnd = "left_handMidEnd_joint"
    case leftHandPinkyStart = "left_handPinkyStart_joint"
    case leftHandPinky1 = "left_handPinky_1_joint"
    case leftHandPinky2 = "left_handPinky_2_joint"
    case leftHandPinky3 = "left_handPinky_3_joint"
    case leftHandPinkyEnd = "left_handPinkyEnd_joint"
    case leftHandRingStart = "left_handRingStart_joint"
    case leftHandRing1 = "left_handRing_1_joint"
    case leftHandRing2 = "left_handRing_2_joint"
    case leftHandRing3 = "left_handRing_3_joint"
    case leftHandRingEnd = "left_handRingEnd_joint"
    case leftHandThumbStart = "left_handThumbStart_joint"
    case leftHandThumb1 = "left_handThumb_1_joint"
    case leftHandThumb2 = "left_handThumb_2_joint"
    case leftHandThumbEnd = "left_handThumbEnd_joint"
    case neck1 = "neck_1_joint"
    case neck2 = "neck_2_joint"
    case neck3 = "neck_3_joint"
    case neck4 = "neck_4_joint"
    case head = "head_joint"
    case jaw = "jaw_joint"
    case chin = "chin_joint"
    case leftEye = "left_eye_joint"
    case leftEyeLowerLid = "left_eyeLowerLid_joint"
    case leftEyeUpperLid = "left_eyeUpperLid_joint"
    case leftEyeball = "left_eyeball_joint"
    case nose = "nose_joint"
    case rightEye = "right_eye_joint"
    case rightEyeLowerLid = "right_eyeLowerLid_joint"
    case rightEyeUpperLid = "right_eyeUpperLid_joint"
    case rightEyeball = "right_eyeball_joint"
    case rightShoulder = "right_shoulder_1_joint"
    case rightArm = "right_arm_joint"
    case rightForearm = "right_forearm_joint"
    case rightHand = "right_hand_joint"
    case rightHandIndexStart = "right_handIndexStart_joint"
    case rightHandIndex1 = "right_handIndex_1_joint"
    case rightHandIndex2 = "right_handIndex_2_joint"
    case rightHandIndex3 = "right_handIndex_3_joint"
    case rightHandIndexEnd = "right_handIndexEnd_joint"
    case rightHandMidStart = "right_handMidStart_joint"
    case rightHandMid1 = "right_handMid_1_joint"
    case rightHandMid2 = "right_handMid_2_joint"
    case rightHandMid3 = "right_handMid_3_joint"
    case rightHandMidEnd = "right_handMidEnd_joint"
    case rightHandPinkyStart = "right_handPinkyStart_joint"
    case rightHandPinky1 = "right_handPinky_1_joint"
    case rightHandPinky2 = "right_handPinky_2_joint"
    case rightHandPinky3 = "right_handPinky_3_joint"
    case rightHandPinkyEnd = "right_handPinkyEnd_joint"
    case rightHandRingStart = "right_handRingStart_joint"
    case rightHandRing1 = "right_handRing_1_joint"
    case rightHandRing2 = "right_handRing_2_joint"
    case rightHandRing3 = "right_handRing_3_joint"
    case rightHandRingEnd = "right_handRingEnd_joint"
    case rightHandThumbStart = "right_handThumbStart_joint"
    case rightHandThumb1 = "right_handThumb_1_joint"
    case rightHandThumb2 = "right_handThumb_2_joint"
    case rightHandThumbEnd = "right_handThumbEnd_joint"
}
